### ISSUE TITLE
Usage without homeassistant

### ISSUE THREAD

**Issue by sebascha** [grocy/grocy-pyscanner#3]
Hy,
are there any advices for users who dont use homeassistant? 
I set up all variables except homeassistant token and get the following output:
```
400
Traceback (most recent call last):
  File "barcode_reader.py", line 309, in <module>
    decrease_inventory(upc)
  File "barcode_reader.py", line 69, in decrease_inventory
    product_id_lookup(upc)
  File "barcode_reader.py", line 110, in product_id_lookup
    if homeassistant_token != '':
NameError: global name 'homeassistant_token' is not defined
```

And Yes, i am absolutely new to this. :-)

**Comment by TheFuzz4** [comment]
I will have to take a look at the code for this and I'll provide an update here as soon as I do.  I'll be in touch here in about a day or so.

**Comment by berrnd** [comment]
Closing this due to this project is going to be retired.
