### ISSUE TITLE
Cannot run script

### ISSUE THREAD

**Issue by rpbx** [grocy/grocy-pyscanner#4]
Hello,

I am getting an error.

087692009900
Looking up the product_id
404
Traceback (most recent call last):
  File "./barcode_reader.py", line 309, in <module>
    decrease_inventory(upc)
  File "./barcode_reader.py", line 69, in decrease_inventory
    product_id_lookup(upc)
  File "./barcode_reader.py", line 114, in product_id_lookup
    j = r.json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 898, in                                                                                                                                                              json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 4 - line 1 column 15 (char 3 - 14)
Exception TypeError: TypeError('super() takes at least 1 argument (0 given)',) i                                                                                                                                                             n <bound method InputDevice.__del__ of InputDevice('/dev/input/event0')> ignored

I am running it on a raspberrypi 4.

Also, what value am I supposed to enter by "UPC_DATABASE_API=?

Thank you

**Comment by TheFuzz4** [comment]
For the UPC database Api you'll have to register an account there and request it.  Not sure if the pi model is an issue or not but all I have access to is just 3's at the moment. 

I'm not entirely sure whats causing this error to throw but I"ll take a look here and see what I can figure out.

**Comment by rpbx** [comment]
Can the problem be that I am using SSL?
Is there a way for me to get it to work over SSL?
Thank you

**Comment by berrnd** [comment]
Closing this due to this project is going to be retired.
