### ISSUE TITLE
something is not working .. 

### ISSUE THREAD

**Issue by Simon-CR** [grocy/grocy-pyscanner#5]
unknown key, scancode=42
unknown key, scancode=45
unknown key, scancode=42
unknown key, scancode=18
unknown key, scancode=42
unknown key, scancode=23
unknown key, scancode=42
unknown key, scancode=23
unknown key, scancode=42
unknown key, scancode=32
XX002XX3XXXX8XX
Looking up the product_id
405
Traceback (most recent call last):
  File "barcode_reader.py", line 309, in <module>
    decrease_inventory(upc)
  File "barcode_reader.py", line 69, in decrease_inventory
    product_id_lookup(upc)
  File "barcode_reader.py", line 116, in product_id_lookup
    product_id = j['product']['id']
KeyError: 'product'
Exception TypeError: TypeError('super() takes at least 1 argument (0 given)',) in <bound method InputDevice.__del__ of InputDevice('/dev/input/event0')> ignored

the product code i'm trying to scan is YHDAA-tech

I pre-added it to my grocy inventory list with a few quantity in there

**Comment by berrnd** [comment]
Closing this due to this project is going to be retired.
